[package]
name = "soldank"
version = "0.1.0"
authors = ["helloer <im.helloer@gmail.com>"]

[dependencies]
nalgebra = "0.14.0"
byteorder = "1.2.1"
gfx2d = { path = "gfx2d" }
gfx = "0.17.1"
gfx_window_glutin = "0.20.0"
glutin = "0.12.1"
image = "0.18.0"
time = "0.1"
rust-ini = "0.10"
