[package]
name = "gfx2d"
version = "0.1.0"
authors = ["Mariano Cuatrin <mariano.cuatrin@gmail.com>"]

[dependencies]
gfx = "0.18.1"
gfx_core = "0.9.1"
gfx_device_gl = "0.16.1"
gfx_window_glutin = "0.31.0"
glutin = "0.21"
image = "0.21.2"
cgmath = "0.17"
