[package]
name = "gfx2d"
version = "0.1.0"
authors = ["Mariano Cuatrin <mariano.cuatrin@gmail.com>"]

[dependencies]
gfx = "0.17.1"
gfx_core = "0.8.2"
gfx_device_gl = "0.15"
gfx_window_glutin = "0.20.0"
glutin = "0.12.1"
image = "0.18.0"
